### ISSUE TITLE
Extract value from input fields

### ISSUE THREAD

**Issue by cbroughton80** [pdulvp/extract-data#35]
Extracting data from textarea form fields works, I'm assuming because the data is held in between two html tags. It would be handy to be able to extract the value from an input field for sites that return data with a prefilled form.

**Comment by pdulvp** [comment]
Hi, indeed this seems handy.
With upcoming version, i have added extraction of attributes

![image](https://user-images.githubusercontent.com/28950124/111533568-3675c080-8767-11eb-8638-b190192b8855.png)
